### ISSUE TITLE
Misuse cases

### ISSUE THREAD

**Issue by chramostatm** [22FAUNO-SA-Team-1/ClassProjectDocuments#10]
See Team OneNote for full description of this portion.

Each Team member should find 1 use/misuse case and develop material for said case.
Please leave a Comment here with status updates.

**Comment by schaafcl** [comment]
I'm going to claim "Creating an authorized user" for now as my issue

**Comment by ekuether** [comment]
I'll take the use case of user authentication

**Comment by chramostatm** [comment]
I'll delve into "Hosting a Keycloak Server"

**Comment by jk1850** [comment]
I'll be covering "Creating a truststore"

**Comment by zrlange** [comment]
I will be covering "Creating a Realm"

**Comment by chramostatm** [comment]
Uploaded my diagram. Feel free to critique here or in discord.

**Comment by schaafcl** [comment]
v1 of my diagram is up, comments welcome here or on discord

**Comment by zrlange** [comment]
I just finished my misuse case and added some information to the OSS security documentation section. I have a spell checker plug-in in VS Code, so I also corrected anything it flagged while I was in there. Coming together nicely.

**Comment by chramostatm** [comment]
Pushed my use case draft

**Comment by chramostatm** [comment]
Closing issue. Will do a final proofread/review of everything, before Submission. See Issue#14 for changes
