### ISSUE TITLE
P1 Reflection

### ISSUE THREAD

**Issue by chramostatm** [22FAUNO-SA-Team-1/ClassProjectDocuments#11]
Assess alignment of security requirements with advertised features. Review OSS project documentation and codebase to support your observations.

**Comment by chramostatm** [comment]
Noted ekuther submission at commit 907ba88. Will review.

**Comment by ekuether** [comment]
In my commit, I added the security requirement review that Keycloak has implemented.

**Comment by chramostatm** [comment]
Closing issue. Will do a final proofread/review of everything, before Submission. See Issue#14 for changes
