### ISSUE TITLE
OSS Documentation Review

### ISSUE THREAD

**Issue by chramostatm** [22FAUNO-SA-Team-1/ClassProjectDocuments#12]
Review OSS project documentation for security-related configuration and installation issues. Summarize your observations.

**Comment by chramostatm** [comment]
@zrlange , @jk1850 what is the //TODO doing in this section? I think your section looks good. I can delete it if you're alright with it.

**Comment by zrlange** [comment]
@chramostatm The TODO is to remind me that I need to add a little more information to the documentation I linked right above it. Since that section is 20% of the grade I am hesitant to leave the section as is.

**Comment by chramostatm** [comment]
@zrlange fair enough.

**Comment by chramostatm** [comment]
Closing issue. Will do a final proofread/review of everything, before Submission. See Issue#14 for changes
