### ISSUE TITLE
Planning and Refection

### ISSUE THREAD

**Issue by chramostatm** [22FAUNO-SA-Team-1/ClassProjectDocuments#13]
Overall team planning and Individual Contribution 
- Link github issues/individual assignments 
- Discuss any catch points or difficulties, and how we overcame them

**Comment by schaafcl** [comment]
First draft of reflection and planning is up.  Trenton feel free to add anything you want before final review.

**Comment by chramostatm** [comment]
Closing issue. Will do a final proofread/review of everything. Before Submission. See Issue#14 for changes
