### ISSUE TITLE
P1 Top Level Claims

### ISSUE THREAD

**Issue by chramostatm** [22FAUNO-SA-Team-1/ClassProjectDocuments#15]
Top-level claims pertain to critical properties of the system that are worth arguing. The claims are properly worded.

**Comment by ekuether** [comment]
I'll take the claim that the software mitigates any database theft

**Comment by schaafcl** [comment]
My top level claim is - users will be properly authenticated, Initial diagram is up pending review

**Comment by jk1850** [comment]
I'll be covering the man-in-the-middle prevention case.

**Comment by chramostatm** [comment]
Noted all Top Level claims are up. Closing issue.
