### ISSUE TITLE
Code Review strategy

### ISSUE THREAD

**Issue by chramostatm** [22FAUNO-SA-Team-1/ClassProjectDocuments#29]

**Comment by chramostatm** [comment]
Added myself to this as well. I worked on the Automated Scan Strategy a subsection of Code Review Strategy.

**Comment by schaafcl** [comment]
Initial submission added and awaiting group review

**Comment by chramostatm** [comment]
Closing issue. Will talk in the group meeting tonight and modify where necessary in the final review. Thanks @schaafcl!
