### ISSUE TITLE
Team collaboration

### ISSUE THREAD

**Issue by chramostatm** [22FAUNO-SA-Team-1/ClassProjectDocuments#34]
Include a link to your team's GitHub repository that shows your internal project task assignments and collaborations to finish this task. 
Include a reflection of your teamwork for this assignment. What issues occurred? How did you resolve them? What did you plan to change moving forward?

**Comment by schaafcl** [comment]
Initial submissions complete and awaiting group review

**Comment by chramostatm** [comment]
Closing issue. Will talk in the group meeting tonight and modify where necessary in the final review. Thanks @schaafcl!
